db.url=jdbc:postgresql://localhost:5444/my_db
db.username=root
db.password=root
db.driver=org.postgresql.Driver

hikari.maximumPoolSize=10
hikari.minimumIdle=2
hikari.idleTimeout=30000
hikari.connectionTimeout=30000